### ISSUE TITLE
SyntaxError: Parse error when running specs

### ISSUE THREAD

**Issue by baphled** [johnbintz/jasmine-headless-webkit#94] opened 2011-12-08 16:56 UTC
I have an existing project that I have just updated jasmine-headless-webkit. All my specs where green prior to the upgrade and I have updated my jasmine.yml to reflect the changes. When I run my specs I now get faced with the following error:

`SyntaxError: Parse error`

The error seems to be triggered from within Jasmine::Headless::Runner on line 90 `system jasmine_command(run_targets)` but I am having trouble getting to the bottom of how to fix this or work around it.

Here's a [gist](https://gist.github.com/1447556) with my Gemfile content along with the output from jasmine-headless-webkit -l and my jasmine.yml config.

Any pointers would be great.

**Comment by johnbintz** [comment] 2011-12-08 18:21
## Try running with the --keep option to preserve the HTML runner, then open the HTML file in anotgher browser to get a real stack trace. FF and Chrome do well with that.

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

Yomi Colledge reply@reply.github.com wrote:

I have an existing project that I have just updated jasmine-headless-webkit. All my specs where green prior to the upgrade and I have updated my jasmine.yml to reflect the changes. When I run my specs I now get faced with the following error:

`SyntaxError: Parse error`

The error seems to be triggered from within Jasmine::Headless::Runner on line 90 `system jasmine_command(run_targets)` but I am having trouble getting to the bottom of how to fix this or work around it.

Here's a [gist](https://gist.github.com/1447556) with my Gemfile content along with the output from jasmine-headless-webkit -l and my jasmine.yml config.

Any pointers would be great.

---

Reply to this email directly or view it on GitHub:
https://github.com/johnbintz/jasmine-headless-webkit/issues/94

**Comment by baphled** [comment] 2011-12-08 18:50
Strange, I still get the parse error but opening the runner actually runs my tests (a few are failing)

I'll get those passing and see if I still get the same parse error.

Thanks for the speedy response :)

**Comment by johnbintz** [comment] 2011-12-08 19:10
If it isn't a JHW problem that you've found, then you can blame this on QtWebKit's JavaScript engine, which doesn't give useful stack traces. Yet. `--keep` and running files in a real browser is, unfortunately, the only good solution for solving issues like this.

**Comment by baphled** [comment] 2011-12-08 19:28
Appreciated, it's still better than having to compile everything manually :D.

I think I have found the issue.

It seems there is a snippet of JS that is being injected into the body of the runner.

Here's the [output](https://gist.github.com/1447556#file_runner.html) to the runner, it's quite long but you will see the issue just at the top.

Hope that helps.

**Comment by johnbintz** [comment] 2011-12-08 19:38
That...is bizarre. O_o This is going to take a bit of research and experimentation. Does a simple test suite work OK on your system?

**Comment by johnbintz** [comment] 2011-12-08 19:39
Also, is this the output you'd get from `cat runner.html`, or is this generated source from your browser? With the HTMLRunner bit at the bottom, I'm guessing it's the latter?

**Comment by baphled** [comment] 2011-12-08 20:08
Your right, the source is generated from my browser.

I haven't had a chance to try it on a clean build but the specs where working fine before I did an update and I have other branches that have the same specs which run perfectly.

After looking into it a little more the output was actually from one of my JST templates, so it appears the HTML is breaking somewhere down the line. I've updated the gist with the actual source created using --keep and I'll dig into a little more to see what is actually going on

**Comment by johnbintz** [comment] 2011-12-08 20:13
OK. If the issue is with template generation and you can get it narrowed down to a specific template that's breaking, and it's not just an error on your end (you never know...), we can figure out the next course of action (patch Sprockets, work around it in JHW, or update docs).

Thanks for digging into it!

**Comment by baphled** [comment] 2011-12-08 20:41
Cracked it.

Seems I had a closing script tag lingering in one of my templates (line 46 of [my gist](https://gist.github.com/1447556#file_jhw.html)) which caused the parse error and broken specs.

Thanks for the input, I wouldn't of picked up on that otherwise :D, especially as it compiled with no probs prior to the update.

**Comment by johnbintz** [comment] 2011-12-08 20:50
Glad you found it! I'll close this ticket and probably start adding a "debugging" section to the docs for problems such as this.

**Closed as completed by johnbintz** 2011-12-08 20:50 UTC

**Comment by baphled** [comment] 2011-12-08 20:55
Brilliant, totally loving this gem, makes working with JS and CS some more more pleasant :)

**Comment by wcamarao** [comment] 2012-04-20 00:04
Hi...I'm running into a similar case except that my output provided by --keep is a spec runner that works fine in the browser. So I still get the "SyntaxError: Parse error" and can't figure out where it's coming from. Any ideas?

**Comment by johnbintz** [comment] 2012-04-20 12:28
Not really, since you don't get any stack traces. You'll have to do some detective work.

**Comment by wcamarao** [comment] 2012-04-23 06:11
Ok found it. err. That was an encoding issue in a js file in spec/helpers. I was setting helpers: in jasmine.yml to be empty but it was including everything inside it anyway. The default is **/*.js but shouldn't we be able to set it to empty?

**Comment by johnbintz** [comment] 2012-04-23 12:38
Set it to `[]`. If it's `nil`, it gets a default vaue.

**Comment by wcamarao** [comment] 2012-04-25 20:17
Cool, thanks!
