### ISSUE TITLE
I can't build gem on osx

### ISSUE THREAD

**Issue by jeremylightsmith** [johnbintz/jasmine-headless-webkit#50] opened 2011-08-12 07:03 UTC
when I run gem install jasmine-headless-webkit, I get :

```
M08600004:~ xq81$ gem install jasmine-headless-webkit
Building native extensions.  This could take a while...
ERROR:  Error installing jasmine-headless-webkit:
    ERROR: Failed to build gem native extension.

        /Users/xq81/.rvm/rubies/ruby-1.8.7-p334/bin/ruby extconf.rb
/Users/xq81/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/version.rb:143: uninitialized constant Gem (NameError)
    from /Users/xq81/.rvm/gems/ruby-1.8.7-p334/gems/jasmine-headless-webkit-0.6.2/lib/qt/qmake.rb:2:in `require'
    from /Users/xq81/.rvm/gems/ruby-1.8.7-p334/gems/jasmine-headless-webkit-0.6.2/lib/qt/qmake.rb:2
    from extconf.rb:5:in `require'
    from extconf.rb:5
```

I have QT installed, I tried first with homebrew, and then with macports.  When I run qmake -v, I get :

```
QMake version 2.01a
Using Qt version 4.7.1 in /opt/local/lib
```

When I download the latest from git, and go into "ext/jasmine-webkit-specrunner" and run "ruby extconf.rb" it seemed to work, but the gem still isn't installed.

What do I do?

**Comment by johnbintz** [comment] 2011-08-12 14:21
This is a duplicate of #49. I've pushed out 0.6.3 which should fix the Gem requiring issue. Let me know if it doesn't.

**Comment by johnbintz** [comment] 2011-08-15 11:17
Oops, accidentally closed this one. :/

**Closed as completed** 2011-08-23 14:19 UTC
